FROM registry.access.redhat.com/ubi9/go-toolset:1.26.2-1779886993 AS builder
WORKDIR /workspace
COPY go.mod go.sum ./
ENV GOTOOLCHAIN=go1.26.3
USER root
RUN go mod download
COPY pkg/git-service pkg/git-service
COPY cmd/git-service cmd/git-service
RUN CGO_ENABLED=0 go build -buildvcs=false -o /go/bin/git-service cmd/git-service/main.go

FROM registry.access.redhat.com/ubi9-minimal:latest

RUN microdnf install -y git && microdnf clean all

COPY --from=builder /go/bin/git-service /usr/bin

USER 1001

CMD ["git-service"]
EXPOSE 8001
